name: cde_amistad
description: "App para el CDE Amistad"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  video_player: ^2.5.0
  webview_flutter: 4.13.0
  table_calendar: ^3.0.9
  http: ^0.13.6
  permission_handler: ^11.0.0
  font_awesome_flutter: ^10.4.0
  supabase_flutter: 2.7.0
  intl: 0.20.2
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_native_splash: ^2.3.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: true
  ios: true
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icono.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/blanco.png"

  android: true
  ios: true
  fullscreen: true
  android_gravity: top
  android_12:
    color: "#FFFFFF"
    image: "assets/blanco.png"
    android_gravity: top



flutter:
  uses-material-design: true

  assets:
    - assets/videos/splash.mp4
    - assets/imagen_default.jpg
    - assets/icono.png
    - assets/logo_twitter.png
    - assets/splash.png
  fonts:
    - family : 'impact'
      fonts:
        - asset: assets/fonts/Impact.ttf
    - family : 'brush script'
      fonts:
        - asset: assets/fonts/BrushyScript-ALWEg.ttf
    - family : 'bebas neue'
      fonts:
        - asset: assets/fonts/BebasNeue.otf
    - family : 'arial'
      fonts:
        #- asset: assets/fonts/ARIAL.ttf
        - asset: assets/fonts/ARIAL.ttf
          weight: 700

